### ISSUE TITLE
No File Apktool.yml

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eleydur0g13/apktool#9]
```
What steps will reproduce the problem?
1. First, Im decompile settings.apk
2. And I Edit xml and values strings.xml
3. When I Want to Recompile the settings.apk, I see  not apktool.yml and that 
be problem i cannot recompile

What is the expected output? What do you see instead?
 Exception in thread "main" brut.androlib.AndrolibException: brut.directory.PathNotExist: apktool.yml
    at brut.androlib.Androlib.readMetaFile(Androlib.java:164)
    at brut.androlib.Androlib.build(Androlib.java:183)
    at brut.androlib.Androlib.build(Androlib.java:176)
    at brut.apktool.Main.cmdBuild(Main.java:228)
    at brut.apktool.Main.main(Main.java:79)
Caused by: brut.directory.PathNotExist: apktool.yml
    at brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:103)
    at brut.androlib.Androlib.readMetaFile(Androlib.java:160)
    ... 4 more


What version of the product are you using? On what operating system?


Please provide any additional information below.

I USE SAMSUNG GALAXY Y GT-S5370
```

Original issue reported on code.google.com by `ophengal...@gmail.com` on 11 Sep 2013 at 12:36

**Comment by wojtekojtek** [comment]
confirmed. still happens

![Image](https://github.com/user-attachments/assets/b09306db-5c7d-42ae-965d-25f043353e0b)
